
/** @jsx h */

import { h } from "preact";
import { tw } from "@twind";
export default function Footer() {
  return (
    <footer
      className={tw`flex items-center flex-col justify-center w-full border-t text-center py-1`}
    >
      <p className={tw`my-5 text-1xl`}>
        <span
          className={tw`text-lg bg-gray-100 rounded-md font-bold dark:text-black p-2 mr-2`}
        >
          Note:
        </span>
        <span>
          this list generated by{" "}
          <a href="https://commits.top/algeria.html">
            <b className={tw`text-green-500`}>commits.top</b>
          </a>
        </span>
      </p>
      <p className={tw`mx-5 mb-3`}>
        <span className={tw`pb-5 font-mono`}>
          <a href="https://dzgitrs.herokuapp.com/">َAPI</a>
        </span>
        <span>{" "}.{" "}</span>
        <span className={tw`pb-5 font-mono`}>
          <a href="https://github.com/moncefplastin07/githrs">
            Github
          </a>
        </span>
        <span>{" "}.{" "}</span>
        <span className={tw`pb-5 font-mono`}>
          <a href="https://twitter.com/moncefplastin07/">Twitter</a>
        </span>
        <span>{" "}.{" "}</span>
        <span>
          <a href="https://facebook.com/moncefplastin07/">Facebook</a>
        </span>
      </p>
    </footer>
  );
}
